name: MultiWorlds
main: me.elite.rtpplugin.RTPPlugin
version: 1.0
api-version: 1.16
author: WedrownyElite
depend: [EclipseFactions]
softdepend: [Multiverse-Core]
commands:
  rtp:
    description: Open world teleport UI
  wild:
    description: Open world teleport UI